INSERT INTO author(id,first_name,last_name,email,pen_name) values (1,'tite','kuba','kubo@example.com','Tite Kubo');
select * from author;
INSERT INTO story(id,author_id,name,status,description) values(1,1,'Bleach','Ongoing',"Bleach (stylized as BLEACH) is a Japanese manga series written and illustrated by Tite Kubo. It follows the adventures of a teenager Ichigo Kurosaki, who inherits his parents' destiny after he obtains the powers of a Soul Reaper—a death personification similar to the Grim Reaper—from another Soul Reaper, Rukia Kuchiki.");
select * from story;
INSERT INTO arc(id,story_id,name,description) values (1,1,'Soul society arc','Ichigo goes to soul society, beats up Byakuya, gets thoroughly beat up by Aizen');
INSERT INTO arc(id,story_id,name,description) values (2,1,'Huecomundo arc','Ichigo goes to Huecomundo, beats up a bunch of Espada');
select * from arc;
INSERT INTO race(id,author_id,name,category,description) values(1,1,'Human','Normal humans', 'no different from the humanity of our world.');
INSERT INTO race(id,author_id,name,category,description) values(2,1,'Hollow','Monster','Lost souls with lingering regrets that were unable to move on.');
INSERT INTO race(id,author_id,name,category,description) values(3,1,'Soul Reaper','Humans','Responsible for maintaining the balance of souls in the three realms');
select * from race;
INSERT INTO characters(id,author_id,name,race_id,gender,status,height,weight,age,alignment,description) values(1,1,'Shigekuni Genryuusai Yamamoto',3,'Male','Deceased',21,2.1,2000,'Lawful-Good','The Captain Commander of the 13 Court Guard Squads, the oldest and stronget of the Soul Reapers.');
INSERT INTO characters(id,author_id,name,race_id,gender,status,height,weight,age,alignment,description) values(2,1,'Ichigo Kurosaki',1,'Male','Alive',21,2.1,17,'Lawful-Good',"You know who Ichigo is, I'm not gonna type all that.");
select * from characters;
INSERT INTO traits(character_id,name,description) values (2,'Sample Heading','Sample Desc');
select * from traits;
INSERT INTO world(id,author_id,name,description) values (1,1,'World of the Living','Modern day earth.');
INSERT INTO world(id,author_id,name,description) values (2,1,'Huecomundo','A desolate wasteland which the hollows call home.');
INSERT INTO world(id,author_id,name,description) values (3,1,'Soul Society','Where the souls of the dead, and the soul reapers reside.');
select * from world;
INSERT into location(id,author_id,world_id,category,name,description) values (1,1,1,'Town','Karakura Town','The town where Ichigo lives.');
INSERT into location(id,author_id,world_id,category,name,description) values (2,1,1,'School','Karakura school','The school Ichigo goes to.');
INSERT into location(id,author_id,world_id,category,name,description) values (3,1,1,'City','Sereitei','The home of the Soul Reapers.');
select * from location;
INSERT INTO item(id,author_id,name,rarity,category,description) values (1,1,'Excalibur','Legendary','Weapon','The mythical sword of King Arthur.');
INSERT INTO item(id,author_id,name,rarity,category,description) values (2,1,'Health Potion','Common','Consumable','Common item easily accessible to most people.');
INSERT INTO item(id,author_id,name,rarity,category,description) values (3,1,'Zangetsu','Unique','Weapon',"Ichigo Kurosaki's Zanpakuto");
INSERT INTO item(id,author_id,name,rarity,category,description) values (4,1,'Zanpakuto','Rare','Weapon',"The weapon of the Soul Reapers");
select * from item;
INSERT INTO organization(id,author_id,leader_id,base_location_id,name,description) values (1,1,1,1,'13 Court Guard Squads','The guardians of Soul Society. They reside in the Sereitei and maintain the baance of Souls between the World of the Living and Soul Society');
select * from organization;
INSERT INTO appearance(character_id,arc_id,role,role_description) values(1,1,'Minor Antagonist',"Yamamoto is the pillar of Soul Society. When Ichigo and friends attack, he gives the command to hunt them down. But he ultimately plays no significant role");
INSERT INTO appearance(character_id,arc_id,role,role_description) values(2,1,'Protagonist','Ichigo and Friends invade the Soul Society to save Rukia.');
select * from appearance;
INSERT INTO item_featured_in(item_id,arc_id) values (3,1);
select * from item_featured_in;
INSERT INTO arc_occurs_in(arc_id,location_id) values(1,3);
INSERT INTO arc_occurs_in(arc_id,location_id) values(2,2);
select * from arc_occurs_in;
INSERT INTO race_lives_in(race_id,world_id) values(1,1);
INSERT INTO race_lives_in(race_id,world_id) values(2,2);
INSERT INTO race_lives_in(race_id,world_id) values(3,3);
INSERT INTO race_lives_in(race_id,world_id) values(2,1);
INSERT INTO item_found_in_world(item_id,world_id) values (4,3);
select * from item_found_in_world;